import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/header.module.css'
import Link from 'next/link'
import { motion } from "framer-motion"
import { useState } from 'react'
import Navheader from '@/headrfooter/headersearchsuggestions';
import Homem from './intro';
import Header from '@/headrfooter/header'
import Homecomponentheader2 from '@/homecomponents/homecomponentheader2'
import Toptrndindcryptos from '@/homecomponents/toptrndindcryptos';
import Coinsstatdiv from '@/homecomponents/coinsstatdiv';
import Footer from '@/headrfooter/footer'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  return (
    <>
    <Head>
        <title>TradeY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/y.png"  />
      </Head>
      {
      true?(
      <main >
      <div style={{minHeight:"100vh",height:"auto"}}>
      <Header/>
<Homecomponentheader2/>
<Coinsstatdiv/>
      </div>

<Footer/>
      </main>):(<div style={{width:"100%", height:"100vh",display:"flex",justifyContent:"center",alignItems:"center"}}>
        <Link style={{color:"blue",borderBottom:"2px solid blue"}} href={`/login`}>Please login first</Link>
       </div>)
    }
      
    </>
  )
}
